### PR TITLE
add autocompletion for ubuntu-app-launch

### LINKED ISSUE #5: no auto completion
sometimes it is helpful to start an app from terminal. (e.g. right now the libertine scope has issues and doesn't show icons)

it is possible to start from terminal, but it is a bit cumbersome, because of the non-intuitive appids

with the below completion script, one has autocompletion of app ids. 

``/usr/share/bash-completion/completions/ubuntu-app-launch``

```
# -*- shell-script -*-

function _ubuntu-app-launch()
{
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$(ubuntu-app-launch-appids)" -- ${cur} ) )
} && complete -F _ubuntu-app-launch ubuntu-app-launch
```

It works if I copy it directly onto my device, but I don't really know where to stick it into the source code to have it packaged and installed.

### PR DESCRIPTION
**Pull request by doniks**
fixes https://github.com/ubports/ubuntu-app-launch/issues/5

### CODE REVIEW

**Comment by doniks** [comment]
DO NOT MERGE YET, still testing

**Comment by doniks** [comment]
works ok now. please consider to merge

How I tested:
have ci build it
download the armhf artefact for ubuntu-app-launch
install with ``dpkg`` on my deb device 
starting apps from app scope still works as expected
autocompletion via ``ubuntu-app-lauch [tab][tab]`` in terminal app works as expected
also via adb shell

**Review by NeoTheThird — APPROVED** [review]
LGTM, great job!

**Comment by NeoTheThird** [comment]
Would you be interested to do this for other some other cli tools as well? [Our brand new QA scripts](https://github.com/ubports/ubports-qa-scripts) come to mind ;)

**Comment by doniks** [comment]
@NeoTheThird cando, but can you maybe help me first understand how it's supposed to work : https://github.com/ubports/ubuntu-touch/issues/772

**Pull request merged**
